#config_version=5

#TODO Turn on GI

show_player:
  mode_attract_started:
    backbox_show:
      loops: -1
      speed: 8
    playfield_show:
      loops: -1
      speed: 2
    pop_8_alternate:
      loops: -1
      speed: 8
    top_lanes_sweep:
      loops: -1
      speed: 8
    mid_lights_bounce:
      loops: -1
      speed: 8

  mode_attract_stopped:
    backbox_show:
      action: stop
    playfield_show:
      action: stop
    pop_8_alternate:
      action: stop
    top_lanes_sweep:
      action: stop
    mid_lights_bounce:
      action: stop
