#config_version=5

#        ::::::::  :::    :::  :::::::: ::::::::::: ::::::::
#      :+:    :+: :+:    :+: :+:    :+:    :+:    :+:    :+:
#     +:+        +:+    +:+ +:+    +:+    +:+    +:+
#    +#++:++#++ +#++:++#++ +#+    +:+    +#+    +#++:++#++
#          +#+ +#+    +#+ +#+    +#+    +#+           +#+
#  #+#    #+# #+#    #+# #+#    #+#    #+#    #+#    #+#
#  ########  ###    ###  ########     ###     ########

shots:
  shot_left_side:
    switch: s_midltlane
    show_tokens:
      light: l_ltmidlane
  shot_right_side:
    switch: s_midrtlane
    show_tokens:
      light: l_rtmidlane
  shot_left_special:
    switch: s_ltmidstandup
    show_tokens:
      light: l_ltspecial
  shot_right_special:
    switch: s_rtmidstandup
    show_tokens:
      light: l_rtspecial
  shot_left_lane:
    switch: s_toplaneleft
  shot_mid_lane:
    switch: s_toplanemid
  shot_right_lane:
    switch: s_toplaneright
  shot_eightball:
    switch: s_eightballholeeject
  shot_ball1:
    switch: s_drop1
    show_tokens: l_ball1
  shot_ball2:
    switch: s_drop2
    show_tokens: l_ball2
  shot_ball3:
    switch: s_drop3
    show_tokens: l_ball3
  shot_ball4:
    switch: s_drop4
    show_tokens: l_ball4
  shot_ball5:
    switch: s_drop5
    show_tokens: l_ball5
  shot_ball6:
    switch: s_drop6
    show_tokens: l_ball6
  shot_ball7:
    switch: s_drop7
    show_tokens: l_ball7
  shot_ball9:
    switch: s_drop9
    show_tokens: l_ball9
  shot_ball10:
    switch: s_drop10
    show_tokens: l_ball10
  shot_ball11:
    switch: s_drop11
    show_tokens: l_ball11
  shot_ball12:
    switch: s_drop12
    show_tokens: l_ball12
  shot_ball13:
    switch: s_drop13
    show_tokens: l_ball13
  shot_ball14:
    switch: s_drop14
    show_tokens: l_ball14
  shot_ball15:
    switch: s_drop15
    show_tokens: l_ball15

#        ::::::::  :::    :::  :::::::: :::::::::::
#      :+:    :+: :+:    :+: :+:    :+:    :+:
#     +:+        +:+    +:+ +:+    +:+    +:+
#    +#++:++#++ +#++:++#++ +#+    +:+    +#+
#          +#+ +#+    +#+ +#+    +#+    +#+
#  #+#    #+# #+#    #+# #+#    #+#    #+#
#  ########  ###    ###  ########     ###
#        :::::::::  :::::::::   ::::::::  :::::::::: ::::::::::: :::        :::::::::: ::::::::
#       :+:    :+: :+:    :+: :+:    :+: :+:            :+:     :+:        :+:       :+:    :+:
#      +:+    +:+ +:+    +:+ +:+    +:+ +:+            +:+     +:+        +:+       +:+
#     +#++:++#+  +#++:++#:  +#+    +:+ :#::+::#       +#+     +#+        +#++:++#  +#++:++#++
#    +#+        +#+    +#+ +#+    +#+ +#+            +#+     +#+        +#+              +#+
#   #+#        #+#    #+# #+#    #+# #+#            #+#     #+#        #+#       #+#    #+#
#  ###        ###    ###  ########  ###        ########### ########## ########## ########

shot_profiles:
  eightball:
    states:
    - name: lit
      show: "on"
    - name: unlit
      show: "off"
  special:
    states:
    - name: unlit
      show: "off"
    - name: lit
      show: "on"
    advance_on_hit: false
  left_side:
    states:
    - name: unlit
      show: "off"
    - name: lit
      show: "on"
  right_side:
    states:
    - name: unlit
      show: "off"
    - name: lit
      show: "on"
